# frozen_string_literal: true

# Homebrew cask for Ferrule.app. Generated by `make brew VERSION=vX.Y.Z` in
# github.com/NakliTechie/ferrule from that release's SHA256SUMS — edit the template in
# packaging/brew/, not this file.
#
# The bundle is Apple Silicon only (see the Makefile for why it is not universal). Its
# executable carries the ad-hoc signature the Go linker gives every darwin/arm64 binary
# and nothing more, so the postflight clears the download quarantine and the caveats say
# so. The CLI on its own, and Intel Macs, are the formula of the same name.
cask "ferrule" do
  version "1.1.0"
  sha256 "99f0f186a30d0fdbb9fc626bcc9f35a45547e7c4a518d9f49ec213131ceb2018"

  url "https://github.com/NakliTechie/ferrule/releases/download/v#{version}/Ferrule-macos.zip"
  name "Ferrule"
  desc "Every LLM key held once, encrypted, on your machine, behind one endpoint"
  homepage "https://github.com/NakliTechie/ferrule"

  livecheck do
    url :url
    strategy :github_latest
  end

  depends_on arch: :arm64
  depends_on :macos

  app "Ferrule.app"

  postflight_steps do
    run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{appdir}}/Ferrule.app"]
  end

  caveats <<~EOS
    Ferrule #{version} is not Apple-notarised; macOS cannot name the developer. If it
    is still blocked, open it once with right-click → Open, or run:
      xattr -dr com.apple.quarantine "#{appdir}/Ferrule.app"

    Ferrule.app starts the daemon and opens the panel at http://localhost:8899.
    For the `ferrule` command on its own: brew install naklitechie/tap/ferrule
    Keys live encrypted in ~/.config/ferrule; uninstalling the app does not remove them.
  EOS
end
