# Homebrew formula for Ferrule. Generated by `make brew VERSION=vX.Y.Z` in
# github.com/NakliTechie/ferrule from that release's SHA256SUMS — edit the template in
# packaging/brew/, not this file.
#
# Installs the prebuilt binary from the GitHub release: no Go toolchain, and because
# Homebrew fetches with curl the binary is never quarantined, so there is no Gatekeeper
# step. The Ferrule.app bundle is the cask of the same name.
class Ferrule < Formula
  desc "Every LLM key held once, encrypted, on your machine, behind one endpoint"
  homepage "https://github.com/NakliTechie/ferrule"
  license "MIT"

  livecheck do
    url :stable
    strategy :github_latest
  end

  on_macos do
    on_arm do
      url "https://github.com/NakliTechie/ferrule/releases/download/v1.2.0/ferrule-darwin-arm64"
      sha256 "437d55b83bbdcaa42aaba477f213479b52871524e74bd88135ac301f57b2c726"
    end
    on_intel do
      url "https://github.com/NakliTechie/ferrule/releases/download/v1.2.0/ferrule-darwin-amd64"
      sha256 "943f88007d51be7249dd688ccff98162985b227de81dd2a373f2680f8bda0c56"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/NakliTechie/ferrule/releases/download/v1.2.0/ferrule-linux-arm64"
      sha256 "cb582abc63a710b90d6bef5189727f54dfd28ca70563b0b96de3524e922ecf82"
    end
    on_intel do
      url "https://github.com/NakliTechie/ferrule/releases/download/v1.2.0/ferrule-linux-amd64"
      sha256 "fdfdcad61a1f873886c7793c8f0066d411f03485b8b6786d9b50b1549133e3e0"
    end
  end

  def install
    bin.install Dir["ferrule-*"].first => "ferrule"
  end

  def caveats
    <<~EOS
      Start the daemon with `ferrule serve`; the panel is at http://localhost:8899.
      Keys live encrypted in ~/.config/ferrule and outlive this formula on uninstall.
    EOS
  end

  test do
    assert_match "ferrule v#{version}", shell_output("#{bin}/ferrule --version")
  end
end
