# Homebrew formula for Ferrule. Generated by `make brew VERSION=vX.Y.Z` in
# github.com/NakliTechie/ferrule from that release's SHA256SUMS — edit the template in
# packaging/brew/, not this file.
#
# Installs the prebuilt binary from the GitHub release: no Go toolchain, and because
# Homebrew fetches with curl the binary is never quarantined, so there is no Gatekeeper
# step. The Ferrule.app bundle is the cask of the same name.
class Ferrule < Formula
  desc "Every LLM key held once, encrypted, on your machine, behind one endpoint"
  homepage "https://github.com/NakliTechie/ferrule"
  license "MIT"

  livecheck do
    url :stable
    strategy :github_latest
  end

  on_macos do
    on_arm do
      url "https://github.com/NakliTechie/ferrule/releases/download/v1.1.0/ferrule-darwin-arm64"
      sha256 "4f78a0958e7f7523284e8dc8541298368a8e8d7bbe10a5e3363022884e4f4bf0"
    end
    on_intel do
      url "https://github.com/NakliTechie/ferrule/releases/download/v1.1.0/ferrule-darwin-amd64"
      sha256 "31342f9ad9843b851eeae5c055e88f7f9dbb2e6350468a0deb8fb1bd513cbb5e"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/NakliTechie/ferrule/releases/download/v1.1.0/ferrule-linux-arm64"
      sha256 "114253fd5533f93dd4d70614a48faf1c732f2a0eede560124e194f476756067d"
    end
    on_intel do
      url "https://github.com/NakliTechie/ferrule/releases/download/v1.1.0/ferrule-linux-amd64"
      sha256 "a791605c54c16121e9e350f028afeb5a5c890b2ffb564403afca26cc21320f03"
    end
  end

  def install
    bin.install Dir["ferrule-*"].first => "ferrule"
  end

  def caveats
    <<~EOS
      Start the daemon with `ferrule serve`; the panel is at http://localhost:8899.
      Keys live encrypted in ~/.config/ferrule and outlive this formula on uninstall.
    EOS
  end

  test do
    assert_match "ferrule v#{version}", shell_output("#{bin}/ferrule --version")
  end
end
